# Generated by Django 5.2.5 on 2025-08-28 12:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Геометрия')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL фотографии')),
            ],
            options={
                'verbose_name': 'Объект на карте',
                'verbose_name_plural': 'Объекты на карте',
            },
        ),
    ]
