# Generated by Django 5.2.5 on 2025-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='trip_name',
            field=models.CharField(default='Поездка 1', max_length=255),
        ),
    ]
